# Generated by Django 3.0.6 on 2020-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
