# Generated by Django 3.0.6 on 2020-05-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0003_roomreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='room_id',
            new_name='room',
        ),
    ]
